# Generated by Django 4.1.4 on 2022-12-14 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoctorEmail', models.CharField(max_length=60)),
                ('PatientEmail', models.CharField(max_length=60)),
                ('PostID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Doctors.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoctorEmail', models.CharField(max_length=60)),
                ('PatientEmail', models.CharField(max_length=60)),
                ('Content', models.TextField(blank=True, default='Hi :)', null=True)),
                ('PostID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Doctors.post')),
            ],
        ),
    ]
