# Generated by Django 4.1.4 on 2022-12-14 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=25)),
                ('LastName', models.CharField(max_length=25)),
                ('Email', models.CharField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=60)),
                ('Birthdate', models.DateField()),
                ('ImageProfile', models.ImageField(upload_to='Photos/PatientsProfilesPhoto/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='ChestMRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PredictValue', models.CharField(max_length=60)),
                ('Image', models.ImageField(upload_to='Photos/ChestMRI/%y/%m/%d')),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='BrainMRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PredictValue', models.CharField(max_length=60)),
                ('Image', models.ImageField(upload_to='Photos/BrainMRI/%y/%m/%d')),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Patients.patient')),
            ],
        ),
    ]
